- name: docker build and push
  hosts: 192.168.31.253  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/pets-tore

    - name: tag image
      command: docker tag petstore:latest iivanof/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: iivanof
        password: D0ck3rp@ss

    - name: Push image
      command: docker push iivanof/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 iivanof/petstore:latest
